Add ability to partition pgsql by inheritance
Only the sales table is partitioned by using table inheritance.

diff --git a/src/scripts/pgsql/tsdss-pgsql-create-tables b/src/scripts/pgsql/tsdss-pgsql-create-tables
--- a/src/scripts/pgsql/tsdss-pgsql-create-tables
+++ b/src/scripts/pgsql/tsdss-pgsql-create-tables
@@ -3,7 +3,67 @@
 # Copyright 2017 PostgreSQL Global Development Group
 #
 
-PSQL="psql -v ON_ERROR_STOP=1 -X"
+usage() {
+	echo "Usage: `basename $0` <options>"
+	echo
+	echo "Options:"
+	echo "  -g         Flag to generate datafiles for table partitioning"
+	echo "  -y <int>   Number of years of data that will be generated"
+}
+
+create_child_tables() {
+	Y=0
+	while [ $Y -lt $YEARS ]; do
+		M=0
+		while [ $M -lt 12 ]; do
+			YEAR=$(( 2001 + $Y))
+			MONTH=$(( $M + 1))
+			TABLENAME="sales_${YEAR}_${MONTH}"
+
+			TIME0=`$PSQL -c "SELECT EXTRACT(EPOCH FROM '$YEAR-$MONTH-01'::DATE);"`
+			TIME1=`$PSQL -c "SELECT EXTRACT(EPOCH FROM '$YEAR-$MONTH-01'::DATE + INTERVAL '1' MONTH);"`
+
+			$PSQL <<- __EOF__
+				CREATE TABLE $TABLENAME (
+					CHECK (time_id >= $TIME0 AND time_id < $TIME1)
+				) INHERITS (sales);
+			__EOF__
+
+			if [ $GENERATE_DATA -eq 1 ]; then
+				for FILE in `ls $DATAFILE_PATH/sales.data*`; do
+					awk "(\$3 >= $TIME0 && \$3 < $TIME1) {print}" $FILE \
+							>> $DATAFILE_PATH/sales-$YEAR-$MONTH.data
+				done
+			fi
+
+			M=$(( $M + 1 ))
+		done
+		Y=$(( $Y + 1 ))
+	done
+}
+
+DATAFILE_PATH=""
+GENERATE_DATA=0
+YEARS=""
+while getopts "ghi:y:" OPT; do
+	case $OPT in
+	g)
+		GENERATE_DATA=1
+		;;
+	h)
+		usage
+		exit 0
+		;;
+	i)
+		DATAFILE_PATH=$OPTARG
+		;;
+	y)
+		YEARS=$OPTARG
+		;;
+	esac
+done
+
+PSQL="psql -v ON_ERROR_STOP=1 -X -t --no-align"
 
 $PSQL <<- __EOF__
 CREATE TABLE product (
@@ -45,6 +105,20 @@ RC=$?
 if [ $RC -ne 0 ]; then
 	echo "ERROR: creating tables $RC"
 	exit 1
+fi
+
+if [ -n "$PG_PARTITION" ]; then
+	if [ -z "$YEARS" ]; then
+		echo "ERROR: Expected years of data must be specified with -y"
+		exit 1
+	fi
+
+	if [ "x$PG_PARTITION" = "xinheritance" ]; then
+		create_child_tables
+	else
+		echo "ERROR: Unknown partitioning scheme: $PG_PARTITION"
+		exit 1
+	fi
 fi
 
 exit 0
diff --git a/src/scripts/pgsql/tsdss-pgsql-load-data b/src/scripts/pgsql/tsdss-pgsql-load-data
--- a/src/scripts/pgsql/tsdss-pgsql-load-data
+++ b/src/scripts/pgsql/tsdss-pgsql-load-data
@@ -15,70 +15,113 @@ usage() {
 
 constrain_sales_product()
 {
+	TABLE=$1
+
 	if [ $LINUXPERF -eq 1 ]; then
-		local CMD="$PERFCOMMAND -o $PERFDIR/perf-sales-product-fk.data"
+		local CMD="$PERFCOMMAND -o $PERFDIR/perf-$TABLE-product-fk.data"
 	fi
 	$CMD $PSQL <<- __EOF__
-		ALTER TABLE sales
+		ALTER TABLE $TABLE
 		ADD FOREIGN KEY (product_id)
 		REFERENCES product (id);
 	__EOF__
 	RC=$?
 	if [ $RC -ne 0 ]; then
-		echo "error creating sales/product fk: $RC"
+		echo "error creating $TABLE/product fk: $RC"
 		exit 1
 	fi
 }
 
 constrain_sales_store()
 {
+	TABLE=$1
+
 	if [ $LINUXPERF -eq 1 ]; then
-		local CMD="$PERFCOMMAND -o $PERFDIR/perf-sales-store-fk.data"
+		local CMD="$PERFCOMMAND -o $PERFDIR/perf-$TABLE-store-fk.data"
 	fi
 	$CMD $PSQL <<- __EOF__
-		ALTER TABLE sales
+		ALTER TABLE $TABLE
 		ADD FOREIGN KEY (store_id)
 		REFERENCES store (id);
 	__EOF__
 	RC=$?
 	if [ $RC -ne 0 ]; then
-		echo "error creating sales/store fk: $RC"
+		echo "error creating $TABLE/store fk: $RC"
 		exit 1
 	fi
 }
 
 constrain_sales_time()
 {
+	TABLE=$1
+
 	if [ $LINUXPERF -eq 1 ]; then
-		local CMD="$PERFCOMMAND -o $PERFDIR/perf-sales-time-fk.data"
+		local CMD="$PERFCOMMAND -o $PERFDIR/perf-$TABLE-time-fk.data"
 	fi
 	$CMD $PSQL <<- __EOF__
-		ALTER TABLE sales
+		ALTER TABLE $TABLE
 		ADD FOREIGN KEY (time_id)
 		REFERENCES time (id);
 	__EOF__
 	RC=$?
 	if [ $RC -ne 0 ]; then
-		echo "error creating sales/time fk: $RC"
+		echo "error creating $TABLE/time fk: $RC"
 		exit 1
 	fi
 }
 
 constrain_sales()
 {
-	constrain_sales_product &
-	local PID=$!
-	constrain_sales_store &
-	PID="$PID $!"
-	constrain_sales_time &
-	PID="$PID $!"
+	local PIDS=""
 
-	for P in $PID; do
+	if [ "x$PG_PARTITION" = "xinheritance" ]; then
+		for FILE in `ls $DATAFILE_PATH/sales-*.data`; do
+			local TABLE=`basename ${FILE%.*} | sed -e 's/-/_/g'`
+
+			constrain_sales_product $TABLE &
+			PIDS="$PIDS $!"
+			constrain_sales_store $TABLE &
+			PIDS="$PIDS $!"
+			constrain_sales_time $TABLE &
+			PIDS="$PIDS $!"
+		done
+	else
+		constrain_sales_product sales &
+		PIDS="$PIDS $!"
+		constrain_sales_store sales &
+		PIDS="$PIDS $!"
+		constrain_sales_time sales &
+		PIDS="$PIDS $!"
+	fi
+
+	for P in $PIDS; do
 		wait $P
 		if [ $? -ne 0 ]; then
 			exit 1
 		fi
 	done
+}
+
+load_sales_inheritance()
+{
+	local FILE=$1
+	local TABLE=$2
+
+	if [ $LINUXPERF -eq 1 ]; then
+		local CMD="$PERFCOMMAND -o $PERFDIR/perf-$TABLE.data"
+	fi
+
+	$CMD $PSQL <<- __EOF__
+		BEGIN;
+		TRUNCATE $TABLE;
+		COPY $TABLE FROM '$FILE';
+		COMMIT;
+	__EOF__
+	RC=$?
+	if [ $RC -ne 0 ]; then
+		echo "error loading $TABLE: $RC"
+		exit 1
+	fi
 }
 
 load_table()
@@ -146,7 +189,23 @@ load_product()
 
 load_sales()
 {
-	load_table sales
+	if [ "x$PG_PARTITION" = "xinheritance" ]; then
+		local PIDS=""
+		for FILE in `ls $DATAFILE_PATH/sales-*.data`; do
+			local TABLE=`basename ${FILE%.*} | sed -e 's/-/_/g'`
+			load_sales_inheritance $FILE $TABLE &
+			PIDS="$PIDS $!"
+		done
+
+		for P in $PIDS; do
+			wait $P
+			if [ $? -ne 0 ]; then
+				exit 1
+			fi
+		done
+	else
+		load_table sales
+	fi
 
 	$PSQL -c "VACUUM ANALYZE sales;"
 }
