Add scripts for running a postgres load test

diff --git a/src/scripts/pgsql/tsdss-pgsql-create-tables b/src/scripts/pgsql/tsdss-pgsql-create-tables
--- a/src/scripts/pgsql/tsdss-pgsql-create-tables
+++ b/src/scripts/pgsql/tsdss-pgsql-create-tables
@@ -1,21 +1,11 @@
--- Copyright 2016 2ndQuadrant, Ltd.
--- Copyright 2016 Mark Wong
---
--- This file is part of Touchstone-DSS.
---
--- Touchstone-DSS is free software: you can redistribute it and/or modify
--- it under the terms of the GNU General Public License as published by
--- the Free Software Foundation, either version 3 of the License, or
--- (at your option) any later version.
---
--- Touchstone-DSS is distributed in the hope that it will be useful,
--- but WITHOUT ANY WARRANTY; without even the implied warranty of
--- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--- GNU General Public License for more details.
---
--- You should have received a copy of the GNU General Public License
--- along with Touchstone-DSS.  If not, see <http://www.gnu.org/licenses/>.
+#!/bin/sh
+#
+# Copyright 2017 PostgreSQL Global Development Group
+#
 
+PSQL="psql -v ON_ERROR_STOP=1 -X"
+
+$PSQL <<- __EOF__
 CREATE TABLE product (
     id BIGINT NOT NULL,
     ean CHAR(13) NOT NULL,
@@ -50,3 +40,11 @@ CREATE TABLE time (
     quarter_name CHAR(2) NOT NULL,
     year SMALLINT NOT NULL
 );
+__EOF__
+RC=$?
+if [ $RC -ne 0 ]; then
+	echo "ERROR: creating tables $RC"
+	exit 1
+fi
+
+exit 0
